"""
Simulation Schemas for Synthetic Focus Group — Optimized Production Version

This file defines the structured Pydantic v2 schemas used by the
Persona Factory, Persona Agents, and Analyst Agent. It includes strict
constraints, custom validators, and performance configurations.
"""

import re
import logging
from typing import List
from pydantic import BaseModel, Field, ConfigDict, field_validator, model_validator

logger = logging.getLogger("agentmark.simulation")

# ── Pre-compiled Regex Patterns (Module-level for O(1) compilation overhead) ──
SLUG_REGEX = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

# ── Base Model Config ──────────────────────────────────────────────────────────
SIMULATION_CONFIG = ConfigDict(
    extra="forbid",             # Prevent LLM from hallucinating extra fields
    str_strip_whitespace=True,  # Auto-strip whitespaces and newlines
    validate_assignment=True,   # Re-validate fields if mutated programmatically
    populate_by_name=True       # Allow population by field names or aliases
)


class PersonaProfile(BaseModel):
    """Profile representing a virtual target consumer."""
    model_config = SIMULATION_CONFIG

    id: str = Field(
        ..., 
        max_length=50,
        description="Unique URL-friendly slug (e.g., 'rajesh-45-real-estate')"
    )
    name: str = Field(
        ..., 
        max_length=100,
        description="Realistic local name based on target region"
    )
    age: int = Field(
        ..., 
        ge=1, 
        le=100, 
        description="Age matching target segment"
    )
    occupation: str = Field(
        ..., 
        max_length=100, 
        description="Specific job title"
    )
    income_bracket: str = Field(
        ..., 
        max_length=50, 
        description="Income category or range"
    )
    buying_barriers: List[str] = Field(
        ..., 
        min_length=1, 
        max_length=10,
        description="Specific fears/doubts when purchasing"
    )
    trust_triggers: List[str] = Field(
        ..., 
        min_length=1, 
        max_length=10,
        description="Specific elements that build credibility"
    )
    cognitive_profile: str = Field(
        ..., 
        max_length=1500, 
        description="Behavioral instructions for LLM simulation roleplay"
    )

    @field_validator("id")
    @classmethod
    def validate_slug_format(cls, value: str) -> str:
        """Enforces URL-friendly alphanumeric slug format, auto-correcting separators."""
        # Replace underscores and spaces with hyphens, convert to lowercase
        cleaned = value.strip().replace("_", "-").replace(" ", "-").lower()
        # Collapse multiple hyphens into a single hyphen and strip trailing/leading hyphens
        cleaned = re.sub(r"-+", "-", cleaned).strip("-")
        
        if not SLUG_REGEX.match(cleaned):
            raise ValueError(f"id must be a valid lowercase slug (e.g. 'rajesh-45'). Got: {value}")
        return cleaned


class PersonaCritique(BaseModel):
    """Critique output from an individual persona auditing copy."""
    model_config = SIMULATION_CONFIG

    persona_id: str = Field(
        ..., 
        max_length=50,
        description="Reference to the persona ID"
    )
    resonance_score: int = Field(
        ..., 
        ge=0, 
        le=100, 
        description="Score from 0 to 100 on alignment with needs"
    )
    objection: str = Field(
        ..., 
        min_length=10, 
        max_length=1000, 
        description="Main objection or reason for hesitation"
    )
    clash_quote: str = Field(
        ..., 
        max_length=500, 
        description="Direct quote from the ad copy that triggered the objection"
    )
    click_intent: bool = Field(
        ..., 
        description="True if they would click, False if they would scroll past"
    )
    verdict: str = Field(
        ..., 
        min_length=10, 
        max_length=1000, 
        description="Short explanation of their final decision"
    )


class ActionableRecommendation(BaseModel):
    """Actionable advice generated by the Analyst Agent."""
    model_config = SIMULATION_CONFIG

    target_channel: str = Field(
        ..., 
        max_length=50,
        description="Target marketing channel (e.g., 'LinkedIn', 'Instagram', 'Email')"
    )
    friction_identified: str = Field(
        ..., 
        min_length=10, 
        max_length=1000, 
        description="Specific objection or gap found"
    )
    suggested_revision: str = Field(
        ..., 
        min_length=10, 
        max_length=2000, 
        description="Rewrite copy suggestion to resolve friction"
    )


class FocusGroupReport(BaseModel):
    """Consolidated report output from the simulation analyst."""
    model_config = SIMULATION_CONFIG

    overall_score: int = Field(
        ..., 
        ge=0, 
        le=100, 
        description="Weighted average of all resonance scores (negativity-biased)"
    )
    persona_critiques: List[PersonaCritique] = Field(
        ..., 
        min_length=1, 
        max_length=10,
        description="Individual critiques from the panel"
    )
    actionable_recommendations: List[ActionableRecommendation] = Field(
        ...,
        min_length=1,  # Fix #6: must always have at least 1 recommendation
        max_length=10,
        description="Detailed text revision tips — at least 1 required"
    )
    personas: List[PersonaProfile] = Field(
        default=[],
        description="The simulated persona profiles used for the focus group."
    )

    @model_validator(mode="after")
    def validate_overall_score_boundary(self) -> "FocusGroupReport":
        """
        Validates that the overall score is mathematically logical 
        based on individual critique scores.
        """
        if not self.persona_critiques:
            return self

        max_score = max(c.resonance_score for c in self.persona_critiques)
        min_score = min(c.resonance_score for c in self.persona_critiques)
        
        if self.overall_score > max_score:
             raise ValueError(
                 f"overall_score ({self.overall_score}) cannot be greater than the "
                 f"maximum individual critique score ({max_score})"
             )
        if self.overall_score < min_score:
             raise ValueError(
                 f"overall_score ({self.overall_score}) cannot be lower than the "
                 f"minimum individual critique score ({min_score})"
             )
        return self

    @model_validator(mode="after")
    def validate_persona_id_references(self) -> "FocusGroupReport":
        """
        Fix #10: Cross-validates that all persona_critiques reference valid persona IDs.
        Logs a warning for orphaned critiques instead of crashing,
        preserving graceful degradation.
        """
        if not self.personas or not self.persona_critiques:
            return self
        
        known_ids = {p.id for p in self.personas}
        for critique in self.persona_critiques:
            if critique.persona_id not in known_ids:
                logger.warning(
                    "PersonaCritique references unknown persona_id '%s'. Known IDs: %s",
                    critique.persona_id,
                    list(known_ids)
                )
        return self


class AnalystSynthesis(BaseModel):
    """Lightweight structured output schema for the Analyst LLM call.
    
    Intentionally excludes personas and persona_critiques to reduce
    output token usage and prevent LLM truncation on large panels.
    """
    model_config = SIMULATION_CONFIG

    overall_score: int = Field(
        ..., 
        ge=0, 
        le=100, 
        description="Weighted average of all resonance scores"
    )
    actionable_recommendations: List[ActionableRecommendation] = Field(
        ...,
        min_length=1,  # Fix #6: at least 1 recommendation required
        max_length=10,
        description="Detailed text revision tips to resolve friction — provide at least 1"
    )


class PersonaListContainer(BaseModel):
    """Container schema for generating a list of exactly 5 customer personas."""
    model_config = SIMULATION_CONFIG

    personas: List[PersonaProfile] = Field(
        ..., 
        min_length=5, 
        max_length=5, 
        description="List of exactly 5 distinct target customer personas"
    )
