import React, { useState } from 'react';
import { Download, Calendar, Copy, Check, Code, Package, ShieldCheck, FileDown, ThumbsUp, FileText, LineChart, Map, CalendarDays, ListTodo, LayoutGrid } from 'lucide-react';
import toast from 'react-hot-toast';
import { ChannelIcon } from '../../../../../../shared/ChannelIcon';

interface PublisherContentProps {
  data?: any;
  campaignName?: string;
}

const PublisherContent: React.FC<PublisherContentProps> = ({ data, campaignName }) => {
  const hasRealData = data && Object.keys(data).length > 0;
  const publishingDecision = data?.publishing_decision || '';
  const decisionRationale = data?.decision_rationale || '';
  const publishingPlan = data?.publishing_plan || [];
  const contentCalendar = data?.content_calendar || {};
  const assetChecklist = data?.asset_checklist || {};
  const projectedMetrics = data?.projected_metrics || {};
  const executiveSummary = data?.executive_summary || '';

  const assets = data?.assets || data?.placements || [];
  const qualityScore = data?.quality_score || data?.score || 0;
  const generatedDate = data?.generated_date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  // Only render real AI-generated assets — no hardcoded fallbacks
  const displayAssets = Array.isArray(assets) && assets.length > 0 ? assets : [];

  // ─── Copy single asset ────────────────────────────────────────────────────
  const handleCopyAsset = async (asset: any, idx: number) => {
    const parts: string[] = [];
    const label = `${asset.platform || asset.channel} ${asset.type || 'Asset'}`;
    parts.push(`=== ${label.toUpperCase()} ===`, '');
    if (asset.subject) parts.push(`Subject: ${asset.subject}`, '');
    if (asset.preview || asset.content) parts.push(asset.preview || asset.content, '');
    if (asset.hashtags?.length) parts.push(asset.hashtags.join(' '));
    if (asset.replies) parts.push(`(${asset.replies})`);
    const text = parts.join('\n').trim();

    try {
      await navigator.clipboard.writeText(text);
      setCopiedIdx(idx);
      toast.success(`${label} copied to clipboard!`, { id: 'copy-success' });
      setTimeout(() => setCopiedIdx(null), 2500);
    } catch {
      try {
        const ta = document.createElement('textarea');
        ta.value = text;
        ta.style.cssText = 'position:fixed;opacity:0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        setCopiedIdx(idx);
        toast.success(`${label} copied to clipboard!`, { id: 'copy-success' });
        setTimeout(() => setCopiedIdx(null), 2500);
      } catch {
        toast.error('Unable to copy — please copy manually.', { id: 'copy-success' });
      }
    }
  };

  // ─── Download Markdown ────────────────────────────────────────────────────
  const handleDownloadAll = () => {
    setDownloading(true);
    toast.loading('Preparing campaign package...', { id: 'download', duration: 3000 });
    try {
      const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      const lines: string[] = [];
      lines.push(`# ${campaignName || 'Campaign'} — Complete Campaign Package`);
      lines.push(`> Generated by AgentMark AI on ${now}`, '', '---', '');
      if (publishingDecision) {
        const lbl = publishingDecision === 'APPROVED_FOR_PUBLISHING' ? '✅ APPROVED FOR PUBLISHING' : publishingDecision === 'HOLD' ? '🔴 HOLD' : '⚠️ REVISIONS NEEDED';
        lines.push(`## Publishing Decision\n\n**${lbl}**`);
        if (decisionRationale) lines.push(`\n${decisionRationale}`);
        lines.push('');
      }
      if (executiveSummary) lines.push(`## Executive Summary\n\n${executiveSummary}\n`);
      if (qualityScore > 0) lines.push(`## Quality Score\n\n**${qualityScore.toFixed(1)} / 10**\n`);
      if (projectedMetrics.total_reach) {
        lines.push('## Projected Metrics\n');
        if (projectedMetrics.total_reach) lines.push(`- **Total Reach:** ${projectedMetrics.total_reach}`);
        if (projectedMetrics.lead_target) lines.push(`- **Lead Target:** ${projectedMetrics.lead_target}`);
        if (projectedMetrics.estimated_ctr) lines.push(`- **Est. CTR:** ${projectedMetrics.estimated_ctr}`);
        if (projectedMetrics.estimated_cost) lines.push(`- **Est. Cost:** ${projectedMetrics.estimated_cost}`);
        if (projectedMetrics.roi_projection) lines.push(`- **ROI Projection:** ${projectedMetrics.roi_projection}`);
        if (projectedMetrics.timeline_to_results) lines.push(`- **Timeline:** ${projectedMetrics.timeline_to_results}`);
        lines.push('');
      }
      if (publishingPlan.length > 0) {
        lines.push('## Publishing Plan\n');
        publishingPlan.forEach((plan: any) => {
          lines.push(`### ${plan.channel} — ${plan.content_type}`);
          lines.push(`- **Priority:** ${plan.priority}`, `- **Status:** ${plan.status}`, `- **Frequency:** ${plan.publish_frequency}`, `- **Launch Date:** ${plan.launch_date}`, '');
        });
      }
      if (displayAssets.length > 0) {
        lines.push('## Generated Placements\n');
        displayAssets.forEach((asset: any, i: number) => {
          lines.push(`### ${i + 1}. ${asset.platform || asset.channel} ${asset.type || 'Asset'}`);
          if (asset.subject) lines.push(`**Subject:** ${asset.subject}`, '');
          if (asset.preview || asset.content) lines.push(asset.preview || asset.content);
          if (asset.hashtags?.length) lines.push(`\n${asset.hashtags.join(' ')}`);
          lines.push('');
        });
      }
      lines.push('---', `\n*Generated by AgentMark AI · ${now}*`);
      const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(campaignName || 'campaign').toLowerCase().replace(/\s+/g, '-')}-package.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success('Campaign package downloaded!', { id: 'download' });
    } catch {
      toast.error('Download failed. Please try again.', { id: 'download' });
    } finally {
      setDownloading(false);
    }
  };

  // ─── Build beautiful PDF HTML ─────────────────────────────────────────────
  const buildPublisherPdfHTML = (): string => {
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const esc = (s: string) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>');
    const escRaw = (s: string) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    const section = (title: string, inner: string, accentColor = '#6366F1') => `
      <div class="section" style="--accent:${accentColor}">
        <div class="section-title" style="border-bottom-color:${accentColor};color:#111">${escRaw(title)}</div>
        ${inner}
      </div>`;

    const card = (inner: string) => `<div class="card">${inner}</div>`;
    const grid2 = (items: string[]) => `<div class="grid-2">${items.join('')}</div>`;
    const grid4 = (items: string[]) => `<div class="grid-4">${items.join('')}</div>`;
    const metaRow = (label: string, value: string) =>
      `<div class="meta-row"><span class="meta-label">${escRaw(label)}</span><span>${esc(value)}</span></div>`;
    const badge = (t: string, color = '#6B7280') =>
      `<span class="badge" style="color:${color};background:${color}14;border-color:${color}33">${escRaw(t)}</span>`;

    let sections = '';

    // Decision banner
    if (publishingDecision) {
      const isApproved = publishingDecision === 'APPROVED_FOR_PUBLISHING';
      const isHold = publishingDecision === 'HOLD';
      const color = isApproved ? '#059669' : isHold ? '#DC2626' : '#D97706';
      const bg = isApproved ? '#ECFDF5' : isHold ? '#FEF2F2' : '#FFFBEB';
      const label = isApproved ? '✅ Approved for Publishing' : isHold ? '🔴 Hold' : '⚠️ Revisions Needed';
      sections += `
        <div class="decision-banner" style="background:${bg};border-color:${color}44;color:${color}">
          <div class="decision-label">${label}</div>
          ${decisionRationale ? `<div class="decision-rationale" style="color:#374151">${esc(decisionRationale)}</div>` : ''}
        </div>`;
    }

    // Executive Summary
    if (executiveSummary) {
      sections += section('Executive Summary', `<div class="summary-text">${esc(executiveSummary)}</div>`);
    }

    // Quality Score + Metrics
    const metricCards: string[] = [];
    if (qualityScore > 0) {
      metricCards.push(card(`
        <div class="card-label">Quality Score</div>
        <div style="font-size:36px;font-weight:800;color:#059669;line-height:1;margin-top:6px">${Number(qualityScore).toFixed(1)}<span style="font-size:16px;font-weight:500;color:#6B7280">/10</span></div>
        <div style="font-size:11px;color:#9CA3AF;margin-top:4px">AI Quality Assessment</div>
      `));
    }
    if (projectedMetrics.total_reach) metricCards.push(card(`<div class="card-label">Total Reach</div><div class="metric-val" style="color:#6366F1">${escRaw(projectedMetrics.total_reach)}</div>`));
    if (projectedMetrics.lead_target) metricCards.push(card(`<div class="card-label">Lead Target</div><div class="metric-val" style="color:#059669">${escRaw(projectedMetrics.lead_target)}</div>`));
    if (projectedMetrics.estimated_ctr) metricCards.push(card(`<div class="card-label">Est. CTR</div><div class="metric-val" style="color:#D97706">${escRaw(projectedMetrics.estimated_ctr)}</div>`));
    if (projectedMetrics.estimated_cost) metricCards.push(card(`<div class="card-label">Est. Cost</div><div class="metric-val" style="color:#6B7280">${escRaw(projectedMetrics.estimated_cost)}</div>`));
    if (projectedMetrics.roi_projection) metricCards.push(card(`<div class="card-label">ROI Projection</div><div class="metric-val" style="color:#059669">${escRaw(projectedMetrics.roi_projection)}</div>`));
    if (metricCards.length > 0) {
      sections += section('Metrics & Projections', grid4(metricCards), '#059669');
      if (projectedMetrics.timeline_to_results) {
        sections = sections.replace('</div>\n      </div>', `
          <div style="display:flex;align-items:center;gap:8px;margin-top:14px;padding-top:14px;border-top:1px solid #e5e7eb;font-size:12px;color:#6B7280">
            <span>📅</span><span>Timeline to Results: <strong>${escRaw(projectedMetrics.timeline_to_results)}</strong></span>
          </div>
        </div>\n      </div>`);
      }
    }

    // Publishing Plan
    if (publishingPlan.length > 0) {
      const planCards = publishingPlan.map((plan: any) => {
        const statusColor = plan.status === 'ready' ? '#059669' : '#D97706';
        return `<div class="plan-card">
          <div class="plan-header">
            <div>
              <div class="plan-channel">${escRaw(plan.channel)}</div>
              <div class="plan-sub">${escRaw(plan.content_type)} · ${escRaw(plan.publish_frequency)}</div>
            </div>
            <div style="display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end">
              ${badge(plan.priority + ' Priority')}
              ${badge(plan.status, statusColor)}
            </div>
          </div>
          <div class="plan-grid">
            ${metaRow('Optimal Timing', plan.optimal_timing)}
            ${metaRow('Launch Date', plan.launch_date)}
            ${plan.copy_asset_used ? metaRow('Copy Asset', plan.copy_asset_used) : ''}
            ${plan.visual_asset_used ? metaRow('Visual Asset', plan.visual_asset_used) : ''}
          </div>
          ${plan.kpi_targets && Object.keys(plan.kpi_targets).length > 0 ? `
            <div style="margin-top:10px;padding-top:10px;border-top:1px solid #e5e7eb">
              <div class="meta-label" style="margin-bottom:6px">KPI Targets</div>
              <div style="display:flex;flex-wrap:wrap;gap:6px">
                ${Object.entries(plan.kpi_targets).map(([k, v]) => `<span class="kpi-tag">${escRaw(k)}: ${escRaw(String(v))}</span>`).join('')}
              </div>
            </div>` : ''}
        </div>`;
      }).join('');
      sections += section('Publishing Plan', planCards, '#6366F1');
    }

    // Placements
    if (displayAssets.length > 0) {
      const placementCards = displayAssets.slice(0, 9).map((asset: any) => {
        const platformColor = asset.color || '#6366F1';
        return `<div class="placement-card">
          <div class="placement-header" style="background:${platformColor}12;border-bottom:1px solid ${platformColor}22">
            <div class="placement-platform" style="color:${platformColor}">${escRaw(asset.platform || asset.channel || '')}</div>
            <span class="placement-type">${escRaw(asset.type || 'Asset')}</span>
          </div>
          <div class="placement-body">
            ${asset.subject ? `<div class="placement-subject">${esc(asset.subject)}</div>` : ''}
            <div class="placement-preview">${esc((asset.preview || asset.content || '').substring(0, 280))}${(asset.preview || asset.content || '').length > 280 ? '…' : ''}</div>
            ${asset.hashtags?.length ? `<div class="hashtags">${asset.hashtags.map((h: string) => `<span class="hashtag">${escRaw(h)}</span>`).join('')}</div>` : ''}
            ${asset.replies ? `<div style="font-size:11px;color:#9CA3AF;margin-top:6px">${escRaw(asset.replies)}</div>` : ''}
          </div>
        </div>`;
      }).join('');
      sections += section('Generated Placements', `<div class="placements-grid">${placementCards}</div>`, '#6366F1');
    }

    // Asset Checklist
    if (assetChecklist.copy_assets || assetChecklist.visual_assets) {
      const checklistHtml = grid2([
        assetChecklist.copy_assets ? `
          <div>
            <div class="card-label" style="margin-bottom:10px">Copy Assets</div>
            ${assetChecklist.copy_assets.map((a: any) => `
              <div class="checklist-row">
                <span class="check-icon" style="color:${a.status === 'complete' ? '#059669' : '#D97706'}">${a.status === 'complete' ? '✓' : '○'}</span>
                <span class="check-label">${escRaw(a.asset)}</span>
                <span class="check-status" style="color:${a.status === 'complete' ? '#059669' : '#D97706'}">${escRaw(a.status)}</span>
              </div>`).join('')}
          </div>` : '<div></div>',
        assetChecklist.visual_assets ? `
          <div>
            <div class="card-label" style="margin-bottom:10px">Visual Assets</div>
            ${assetChecklist.visual_assets.map((a: any) => `
              <div class="checklist-row">
                <span class="check-icon" style="color:${a.status === 'complete' ? '#059669' : '#D97706'}">${a.status === 'complete' ? '✓' : '○'}</span>
                <span class="check-label">${escRaw(a.asset)}</span>
                <span class="check-status" style="color:${a.status === 'complete' ? '#059669' : '#D97706'}">${escRaw(a.status)}</span>
              </div>`).join('')}
          </div>` : '<div></div>',
      ]);
      sections += section('Asset Checklist', checklistHtml, '#059669');
    }

    // Content Calendar
    if (contentCalendar.weeks) {
      const weekRows = contentCalendar.weeks.slice(0, 8).map((week: any) => `
        <div class="week-block">
          <div class="week-header">
            <span class="week-label">${escRaw(week.week_label)}</span>
            <span class="week-date">${escRaw(week.week_start_date)}</span>
          </div>
          ${week.theme ? `<div class="week-theme">Theme: ${escRaw(week.theme)}</div>` : ''}
          ${(week.activities || []).map((a: any) => `
            <div class="activity-row">
              <span class="activity-day">${escRaw(a.day)}</span>
              <span class="activity-desc">${escRaw(a.channel)}: ${escRaw(a.description)}</span>
            </div>`).join('')}
        </div>`).join('');
      sections += section('Content Calendar', weekRows, '#6366F1');
    }

    const CSS = `
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Inter', 'Segoe UI', sans-serif; background: #f8f8fc; color: #1a1a2e; font-size: 13px; line-height: 1.6; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .page { max-width: 980px; margin: 0 auto; padding: 32px 44px 60px; }

      /* Cover */
      .cover { display: flex; align-items: center; justify-content: space-between; padding: 28px 36px; margin-bottom: 28px; background: linear-gradient(135deg, #4F46E5 0%, #6366F1 50%, #059669 100%); border-radius: 16px; color: white; }
      .cover-eyebrow { font-size: 10px; font-weight: 700; letter-spacing: .14em; text-transform: uppercase; opacity: .75; margin-bottom: 6px; }
      .cover-title { font-size: 26px; font-weight: 800; line-height: 1.2; }
      .cover-sub { font-size: 12px; opacity: .7; margin-top: 6px; }
      .cover-right { text-align: right; }
      .cover-date { font-size: 11px; opacity: .7; margin-bottom: 8px; }
      .cover-campaign { font-size: 14px; font-weight: 700; }
      .cover-score { display: inline-flex; align-items: baseline; gap: 2px; background: rgba(255,255,255,.18); border: 1px solid rgba(255,255,255,.3); border-radius: 10px; padding: 6px 14px; margin-top: 8px; }
      .cover-score-num { font-size: 22px; font-weight: 800; }
      .cover-score-denom { font-size: 13px; opacity: .75; }

      /* Decision Banner */
      .decision-banner { border: 1.5px solid; border-radius: 12px; padding: 16px 20px; margin-bottom: 20px; }
      .decision-label { font-size: 15px; font-weight: 700; margin-bottom: 6px; }
      .decision-rationale { font-size: 12px; line-height: 1.6; margin-top: 6px; }

      /* Section */
      .section { background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px 24px; margin-bottom: 18px; break-inside: auto; box-shadow: 0 1px 4px rgba(0,0,0,.06); }
      .section-title { font-size: 13px; font-weight: 700; padding-bottom: 10px; margin-bottom: 14px; border-bottom: 2.5px solid; letter-spacing: .02em; }
      .summary-text { font-size: 13px; color: #374151; line-height: 1.75; }

      /* Grids */
      .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
      .grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }

      /* Card */
      .card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 14px 16px; break-inside: avoid; }
      .card-label { font-size: 10px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: #6366F1; margin-bottom: 5px; }
      .metric-val { font-size: 26px; font-weight: 800; margin-top: 4px; line-height: 1; }

      /* Meta */
      .meta-row { display: flex; gap: 10px; align-items: flex-start; margin-bottom: 7px; font-size: 12px; }
      .meta-label { font-size: 10px; font-weight: 600; letter-spacing: .07em; text-transform: uppercase; color: #9CA3AF; min-width: 90px; padding-top: 1px; flex-shrink: 0; }

      /* Badge */
      .badge { font-size: 10px; font-weight: 600; padding: 3px 8px; border-radius: 4px; border: 1px solid; display: inline-block; }

      /* Plan card */
      .plan-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 14px 16px; margin-bottom: 12px; break-inside: avoid; }
      .plan-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px; flex-wrap: wrap; gap: 8px; }
      .plan-channel { font-size: 13px; font-weight: 700; color: #111; }
      .plan-sub { font-size: 11px; color: #9CA3AF; margin-top: 2px; }
      .plan-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }
      .kpi-tag { font-size: 10px; padding: 3px 8px; border-radius: 4px; background: #EEF2FF; color: #4338CA; border: 1px solid #C7D2FE; }

      /* Placements */
      .placements-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
      .placement-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden; break-inside: avoid; }
      .placement-header { padding: 10px 14px; display: flex; align-items: center; justify-content: space-between; }
      .placement-platform { font-size: 12px; font-weight: 700; }
      .placement-type { font-size: 10px; padding: 2px 7px; border-radius: 4px; background: rgba(0,0,0,.06); color: #6B7280; }
      .placement-body { padding: 12px 14px; }
      .placement-subject { font-size: 12px; font-weight: 600; color: #111; margin-bottom: 6px; padding-bottom: 6px; border-bottom: 1px solid #f3f4f6; }
      .placement-preview { font-size: 11px; color: #4b5563; line-height: 1.6; }
      .hashtags { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }
      .hashtag { font-size: 10px; padding: 2px 6px; border-radius: 4px; background: #EEF2FF; color: #4338CA; }

      /* Checklist */
      .checklist-row { display: flex; align-items: center; gap: 8px; padding: 6px 0; border-bottom: 1px solid #f3f4f6; font-size: 12px; }
      .check-icon { font-size: 14px; font-weight: 700; flex-shrink: 0; }
      .check-label { flex: 1; color: #374151; }
      .check-status { font-size: 10px; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; }

      /* Calendar */
      .week-block { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 14px; margin-bottom: 10px; break-inside: avoid; }
      .week-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
      .week-label { font-size: 12px; font-weight: 700; color: #111; }
      .week-date { font-size: 10px; color: #9CA3AF; }
      .week-theme { font-size: 11px; color: #6B7280; margin-bottom: 8px; font-style: italic; }
      .activity-row { display: flex; gap: 8px; align-items: flex-start; margin-bottom: 4px; font-size: 11px; }
      .activity-day { background: #EEF2FF; color: #4338CA; border-radius: 4px; padding: 1px 6px; font-weight: 600; min-width: 50px; text-align: center; flex-shrink: 0; }
      .activity-desc { color: #374151; line-height: 1.5; }

      /* Footer */
      .footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; font-size: 10px; color: #9CA3AF; }

      /* Bullet */
      .bullet { display: flex; align-items: flex-start; gap: 8px; font-size: 12px; color: #4b5563; margin-bottom: 6px; }
      .dot { width: 6px; height: 6px; border-radius: 50%; background: #6366F1; flex-shrink: 0; margin-top: 5px; }

      @page { size: A4; margin: 12mm 12mm; }
      @media print { body { background: white; } .page { padding: 0; } .section, .plan-card, .placement-card, .week-block { box-shadow: none; } }
    `;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>${escRaw(campaignName || 'Campaign')} — Publisher Report</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
  <style>${CSS}</style>
</head>
<body>
<div class="page">

  <!-- Cover -->
  <div class="cover">
    <div>
      <div class="cover-eyebrow">AgentMark AI · Publisher Report</div>
      <div class="cover-title">${escRaw(campaignName || 'Campaign Assets')}</div>
      <div class="cover-sub">AI-generated publishing strategy &amp; placements</div>
    </div>
    <div class="cover-right">
      <div class="cover-date">${today}</div>
      ${qualityScore > 0 ? `
        <div class="cover-score">
          <span class="cover-score-num">${Number(qualityScore).toFixed(1)}</span>
          <span class="cover-score-denom">/10</span>
        </div>` : ''}
    </div>
  </div>

  ${sections}

  <div class="footer">
    <span>Generated by AgentMark AI</span>
    <span>${today}</span>
  </div>

</div>
<script>
  window.onload = function() {
    setTimeout(function() { window.print(); }, 500);
  };
</script>
</body>
</html>`;
  };

  // ─── Export Publisher PDF via hidden iframe ───────────────────────────────
  const handleExportPDF = () => {
    setExportingPdf(true);
    toast.loading('Preparing PDF…', { id: 'pub-pdf', duration: 6000 });
    setTimeout(() => {
      try {
        const html = buildPublisherPdfHTML();
        const iframe = document.createElement('iframe');
        iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:1px;height:1px;opacity:0;border:none;';
        document.body.appendChild(iframe);

        const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
        if (!iframeDoc) {
          toast.error('PDF generation failed. Please try again.', { id: 'pub-pdf' });
          document.body.removeChild(iframe);
          setExportingPdf(false);
          return;
        }

        iframeDoc.open();
        iframeDoc.write(html);
        iframeDoc.close();

        iframe.onload = () => {
          setTimeout(() => {
            iframe.contentWindow?.focus();
            iframe.contentWindow?.print();
            toast.success('Save as PDF from the print dialog!', { id: 'pub-pdf' });
            setExportingPdf(false);
            setTimeout(() => {
              if (document.body.contains(iframe)) document.body.removeChild(iframe);
            }, 60000);
          }, 700);
        };
      } catch {
        toast.error('PDF generation failed. Please try again.', { id: 'pub-pdf' });
        setExportingPdf(false);
      }
    }, 100);
  };

  return (
    <div className="space-y-6 md:space-y-8">
      {/* ── Header ── */}
      <div className="rounded-2xl border border-[#2A2A38] bg-gradient-to-br from-[#111118] via-[#111118] to-[#0A0A0F] p-5 md:p-6 shadow-[0_18px_50px_rgba(0,0,0,0.22)]">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 bg-[#4edea3]/10 border border-[#4edea3]/20 rounded-full px-3 py-1">
              <ShieldCheck size={14} className="text-[#4edea3]" />
              <span className="text-xs uppercase tracking-wider" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#4edea3' }}>Campaign Completed</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-semibold" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{campaignName || 'Campaign Assets'}</h1>
            <p className="text-sm md:text-base flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>
              <Calendar size={14} />Generated on {generatedDate}
            </p>
          </div>
          <div className="flex items-center gap-4 flex-wrap">
            {qualityScore > 0 && (
              <div className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl p-4 flex flex-col items-end shadow-lg">
                <span className="text-xs uppercase tracking-wider mb-1" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Quality Score</span>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#4edea3' }}>{qualityScore.toFixed(1)}</span>
                  <span className="text-sm" style={{ fontFamily: 'Inter, sans-serif', color: '#A0A0D2' }}>/10</span>
                </div>
              </div>
            )}
            <button
              onClick={handleExportPDF}
              disabled={exportingPdf}
              className="px-4 py-2 rounded-lg border border-[#2A2A38] text-sm font-medium transition-all hover:bg-[#1A1A24] flex items-center gap-2 disabled:opacity-50"
              style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F1F1F3' }}
            >
              <FileDown size={16} />
              {exportingPdf ? 'Preparing…' : 'Export PDF'}
            </button>
          </div>
        </div>
      </div>

      {!hasRealData && (
        <div className="bg-[#111118] border border-[#2A2A38] rounded-xl p-4">
          <p className="text-sm" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>
            No publisher data available yet. This will be populated after AI publisher agent completes work.
          </p>
        </div>
      )}

      {/* Publishing Decision */}
      {publishingDecision && (
        <div className={`card-elevate rounded-xl p-6 border ${publishingDecision === 'APPROVED_FOR_PUBLISHING' ? 'bg-[#4edea3]/10 border-[#4edea3]/20' : publishingDecision === 'HOLD' ? 'bg-[#F43F5E]/10 border-[#F43F5E]/20' : 'bg-[#F59E0B]/10 border-[#F59E0B]/20'}`}>
          <h3 className="text-lg font-semibold mb-2 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: publishingDecision === 'APPROVED_FOR_PUBLISHING' ? '#4edea3' : publishingDecision === 'HOLD' ? '#F43F5E' : '#F59E0B' }}>
            <ThumbsUp size={20} />
            {publishingDecision === 'APPROVED_FOR_PUBLISHING' ? 'Approved for Publishing' : publishingDecision === 'HOLD' ? 'Hold' : 'Revisions Needed'}
          </h3>
          {decisionRationale && (
            <p className="text-sm" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{decisionRationale}</p>
          )}
        </div>
      )}

      {/* Executive Summary */}
      {executiveSummary && (
        <div className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl p-6">
          <h3 className="text-lg font-semibold mb-4 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
            <FileText size={20} className="text-[#6366F1]" />
            Executive Summary
          </h3>
          <p className="text-base leading-relaxed" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>{executiveSummary}</p>
        </div>
      )}

      {/* Projected Metrics */}
      {projectedMetrics.total_reach && (
        <div className="card-elevate-green bg-[#111118] border border-[#2A2A38] rounded-xl p-6">
          <h3 className="text-lg font-semibold mb-6 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
            <LineChart size={20} className="text-[#6366F1]" />
            Projected Metrics
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
            {projectedMetrics.total_reach && (<div><span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Total Reach</span><p className="text-2xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#6366F1' }}>{projectedMetrics.total_reach}</p></div>)}
            {projectedMetrics.lead_target && (<div><span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Lead Target</span><p className="text-2xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#4edea3' }}>{projectedMetrics.lead_target}</p></div>)}
            {projectedMetrics.estimated_ctr && (<div><span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Est. CTR</span><p className="text-2xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#F59E0B' }}>{projectedMetrics.estimated_ctr}</p></div>)}
            {projectedMetrics.estimated_cost && (<div><span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Est. Cost</span><p className="text-2xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>{projectedMetrics.estimated_cost}</p></div>)}
            {projectedMetrics.roi_projection && (<div><span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>ROI Projection</span><p className="text-2xl font-bold" style={{ fontFamily: 'Inter, sans-serif', color: '#4edea3' }}>{projectedMetrics.roi_projection}</p></div>)}
          </div>
          {projectedMetrics.timeline_to_results && (
            <div className="flex items-center gap-2 text-sm" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>
              <Calendar size={14} />Timeline: {projectedMetrics.timeline_to_results}
            </div>
          )}
        </div>
      )}

      {/* Publishing Plan */}
      {publishingPlan.length > 0 && (
        <div className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl p-6">
          <h3 className="text-lg font-semibold mb-6 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
            <Map size={20} className="text-[#6366F1]" />
            Publishing Plan
          </h3>
          <div className="space-y-4">
            {publishingPlan.map((plan: any, idx: number) => (
              <div key={idx} className="card-elevate bg-[#0A0A0F] border border-[#2A2A38] rounded-lg p-5">
                <div className="flex items-start justify-between mb-4 flex-wrap gap-2">
                  <div>
                    <h4 className="text-base font-semibold mb-1 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
                      <ChannelIcon channel={plan.channel} size={16} className="text-[#6366F1] shrink-0" />
                      {plan.channel}
                    </h4>
                    <span className="text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{plan.content_type} • {plan.publish_frequency}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs px-2 py-1 rounded bg-[#1A1A24] border border-[#2A2A38]" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{plan.priority} Priority</span>
                    <span className={`text-xs px-2 py-1 rounded ${plan.status === 'ready' ? 'bg-[#4edea3]/10 text-[#4edea3]' : 'bg-[#8B8B9E]/10 text-[#8B8B9E]'}`} style={{ fontFamily: 'JetBrains Mono, monospace' }}>{plan.status}</span>
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div><span className="text-xs uppercase mb-1 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Optimal Timing</span><p style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{plan.optimal_timing}</p></div>
                  <div><span className="text-xs uppercase mb-1 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Launch Date</span><p style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{plan.launch_date}</p></div>
                  {plan.copy_asset_used && <div><span className="text-xs uppercase mb-1 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Copy Asset</span><p style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{plan.copy_asset_used}</p></div>}
                  {plan.visual_asset_used && <div><span className="text-xs uppercase mb-1 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Visual Asset</span><p style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{plan.visual_asset_used}</p></div>}
                </div>
                {plan.kpi_targets && Object.keys(plan.kpi_targets).length > 0 && (
                  <div className="mt-4 pt-4 border-t border-[#2A2A38]">
                    <span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>KPI Targets</span>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(plan.kpi_targets).map(([key, value]: [string, any], kidx: number) => (
                        <span key={kidx} className="px-2 py-1 rounded bg-[#1A1A24] border border-[#2A2A38] text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{key}: {value}</span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Content Calendar */}
      {contentCalendar.weeks && (
        <div className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl p-6">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-semibold flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
              <CalendarDays size={20} className="text-[#6366F1]" />
              Content Calendar
            </h3>
            <span className="text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{contentCalendar.total_weeks} Weeks | {contentCalendar.start_date} - {contentCalendar.end_date || 'Ongoing'}</span>
          </div>
          <div className="space-y-4">
            {contentCalendar.weeks.slice(0, 8).map((week: any, idx: number) => (
              <div key={idx} className="card-elevate bg-[#0A0A0F] border border-[#2A2A38] rounded-lg p-4">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-sm font-semibold" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{week.week_label}</h4>
                  <span className="text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{week.week_start_date}</span>
                </div>
                <p className="text-sm mb-3" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>Theme: {week.theme}</p>
                {week.activities?.length > 0 && (
                  <div className="space-y-2">
                    {week.activities.map((activity: any, aidx: number) => (
                      <div key={aidx} className="flex items-start gap-2 text-xs">
                        <span className="px-2 py-0.5 rounded bg-[#1A1A24] border border-[#2A2A38] min-w-[60px] text-center" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{activity.day}</span>
                        <span style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
                          <ChannelIcon channel={activity.channel} size={12} className="inline mr-1 text-[#6366F1]" />
                          {activity.channel}: {activity.description}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Asset Checklist */}
      {(assetChecklist.copy_assets || assetChecklist.visual_assets) && (
        <div className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl p-6">
          <h3 className="text-lg font-semibold mb-6 flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
            <ListTodo size={20} className="text-[#6366F1]" />
            Asset Checklist
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {assetChecklist.copy_assets && (
              <div>
                <h4 className="text-sm font-medium mb-4" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F1F1F3' }}>Copy Assets</h4>
                <div className="space-y-2">
                  {assetChecklist.copy_assets.map((asset: any, idx: number) => (
                    <div key={idx} className="flex items-center justify-between text-sm p-2 rounded bg-[#0A0A0F] border border-[#2A2A38]">
                      <span style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{asset.asset}</span>
                      <span className={`text-xs px-2 py-0.5 rounded ${asset.status === 'complete' ? 'bg-[#4edea3]/10 text-[#4edea3]' : 'bg-[#F59E0B]/10 text-[#F59E0B]'}`} style={{ fontFamily: 'JetBrains Mono, monospace' }}>{asset.status}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
            {assetChecklist.visual_assets && (
              <div>
                <h4 className="text-sm font-medium mb-4" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F1F1F3' }}>Visual Assets</h4>
                <div className="space-y-2">
                  {assetChecklist.visual_assets.map((asset: any, idx: number) => (
                    <div key={idx} className="flex items-center justify-between text-sm p-2 rounded bg-[#0A0A0F] border border-[#2A2A38]">
                      <span style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{asset.asset}</span>
                      <span className={`text-xs px-2 py-0.5 rounded ${asset.status === 'complete' ? 'bg-[#4edea3]/10 text-[#4edea3]' : 'bg-[#F59E0B]/10 text-[#F59E0B]'}`} style={{ fontFamily: 'JetBrains Mono, monospace' }}>{asset.status}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
          {assetChecklist.missing_assets?.length > 0 && (
            <div className="mt-4 pt-4 border-t border-[#2A2A38]">
              <span className="text-xs uppercase mb-2 block" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F43F5E' }}>Missing Assets</span>
              <div className="flex flex-wrap gap-2">
                {assetChecklist.missing_assets.map((asset: string, idx: number) => (
                  <span key={idx} className="px-2 py-1 rounded bg-[#F43F5E]/10 border border-[#F43F5E]/20 text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F43F5E' }}>{asset}</span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Download All Banner */}
      <div className="bg-[#6366F1]/10 border border-[#6366F1]/20 rounded-xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-[#6366F1]/5 to-transparent pointer-events-none" />
        <div className="flex items-center gap-4 z-10">
          <div className="w-12 h-12 rounded-full bg-[#6366F1]/20 flex items-center justify-center text-[#6366F1]">
            <Package size={26} />
          </div>
          <div>
            <h3 className="text-base md:text-lg font-semibold" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>All Campaign Assets Ready</h3>
            <p className="text-xs md:text-sm mt-1" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>Download a beautifully formatted Markdown document with all placements, plans, and metrics.</p>
          </div>
        </div>
        <button
          onClick={handleDownloadAll}
          disabled={downloading}
          className="w-full sm:w-auto bg-[#6366F1] px-6 py-3 rounded-lg flex items-center justify-center gap-2 transition-opacity hover:opacity-90 z-10 text-sm font-medium shadow-[0_0_20px_rgba(99,102,241,0.3)] disabled:opacity-60"
          style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F1F1F3' }}
        >
          <Download size={18} />
          {downloading ? 'Preparing…' : 'Download Campaign (.md)'}
        </button>
      </div>

      {/* Generated Placements Grid */}
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-lg md:text-xl font-semibold flex items-center gap-2" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>
            <LayoutGrid size={20} className="text-[#6366F1]" />
            Generated Placements
          </h2>
          <span className="bg-[#111118] border border-[#2A2A38] px-3 py-1 rounded-full text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#8B8B9E' }}>{displayAssets.length} Assets</span>
        </div>
        {displayAssets.length === 0 ? (
          <div className="bg-[#111118] border border-[#2A2A38] rounded-xl p-8 flex flex-col items-center justify-center text-center">
            <div className="w-14 h-14 rounded-full bg-[#1A1A24] border border-[#2A2A38] flex items-center justify-center text-[#6366F1] mb-4">
              <Package size={24} />
            </div>
            <p className="text-base font-medium mb-1" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>No placements yet</p>
            <p className="text-sm" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>
              Generated placements will appear here after the AI publisher agent completes its work.
            </p>
          </div>
        ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {displayAssets.slice(0, 9).map((asset: any, idx: number) => {
                return (
                  <div key={idx} className="card-elevate bg-[#111118] border border-[#2A2A38] rounded-xl overflow-hidden group hover:border-[#464554] transition-colors flex flex-col">
                <div className="p-4 border-b border-[#2A2A38] bg-[#1f1f25] flex items-center gap-3">
                  {typeof asset.icon === 'function' ? <asset.icon size={22} className="text-[#6366F1]" /> : <ChannelIcon channel={asset.platform || asset.channel} size={18} className="text-[#6366F1]" />}
                  <span className="text-sm font-bold" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#F1F1F3' }}>{asset.platform || asset.channel} {asset.type || 'Asset'}</span>
                </div>
                <div className="p-5 flex-1 space-y-4">
                  {asset.subject && (<div><span className="text-xs uppercase" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>Subject</span><p className="text-sm mt-1 font-semibold" style={{ fontFamily: 'Inter, sans-serif', color: '#F1F1F3' }}>{asset.subject}</p></div>)}
                  {asset.subject && <div className="w-full h-px bg-[#2A2A38]" />}
                  <p className="text-sm line-clamp-4" style={{ fontFamily: 'Inter, sans-serif', color: '#8B8B9E' }}>{asset.preview || asset.content || 'Content preview'}</p>
                  {asset.hashtags && (
                    <div className="flex flex-wrap gap-2">
                      {asset.hashtags.map((tag: string, tidx: number) => (
                        <span key={tidx} className="bg-[#35343a] px-2 py-1 rounded text-xs" style={{ fontFamily: 'JetBrains Mono, monospace', color: '#A0A0D2' }}>{tag}</span>
                      ))}
                    </div>
                  )}
                  {asset.replies && <span className="text-xs" style={{ fontFamily: 'Inter, sans-serif', color: '#A0A0D2' }}>{asset.replies}</span>}
                </div>
                <div className="p-4 border-t border-[#2A2A38] mt-auto">
                  <button
                    onClick={() => handleCopyAsset(asset, idx)}
                    className="w-full bg-transparent border border-[#2A2A38] px-4 py-2 rounded-lg transition-all flex justify-center items-center gap-2 text-sm hover:bg-[#1A1A24]"
                    style={{ fontFamily: 'JetBrains Mono, monospace', color: copiedIdx === idx ? '#4edea3' : '#F1F1F3', borderColor: copiedIdx === idx ? '#4edea3' : undefined }}
                  >
                    {copiedIdx === idx ? <Check size={16} /> : (asset.action === 'View HTML' ? <Code size={16} /> : <Copy size={16} />)}
                    {copiedIdx === idx ? 'Copied!' : (asset.action || 'Copy')}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
      </div>
    </div>
  );
};

export default React.memo(PublisherContent);
