"""
RESEARCH AGENT - Market Analysis, Competitive Intel & Customized Insights

Role: Market Researcher / Competitive Analyst / Audience Intelligence

INPUT (From Manager Agent + State):
  FROM state:
    ✅ brief: User's campaign brief (context for research insights)
  
  FROM manager_output (fields needed for research):
    ✅ campaign_name: Campaign identifier
    ✅ brand_name: Brand identifier
    ✅ industry: Industry context for market analysis
    ✅ primary_goal: Campaign goal for audience insights
    ✅ target_audience: Detailed audience for customization
    ✅ brand_voice: Tone for personalization
    ✅ channels: Recommended channels from manager
    ✅ deliverables: Recommended deliverables from manager

OUTPUT (5 Fields - JSON - Research foundation for Strategy & Copywriter):
  1. market_analysis: TAM, growth_rate, market_trends (LLM-generated by industry)
  2. competitor_analysis: top_competitors, differentiation_opportunity (LLM-generated)
  3. audience_insights: pain_points, motivations, preferred_channels (LLM-customized)
  4. market_opportunities: Industry-specific growth opportunities (LLM-generated)
  5. recommended_approach: Strategic approach (LLM-personalized)

HOW IT WORKS:
1. Extract fields from manager_output and state
2. Load research prompt template
3. Send campaign context to LLM for analysis
4. LLM generates customized research insights
5. Return 5 fields for Strategy Agent

KEY PRINCIPLE:
Research = AI-Powered Market Intelligence
- LLM analyzes industry, competitors, and audience
- Generates context-aware, specific insights
- No hardcoded data - fully dynamic research
- Uses prompt template from utils/prompts/research_prompt.txt
"""

import logging
logger = logging.getLogger(__name__)

import sys
from pathlib import Path
import json
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add project root to path so imports work
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.state import CampaignState
from llm import get_llm_client
from utils.prompt_loader import load_prompt
from utils.error_handler import safe_llm_call
from schemas import ResearchOutput
from services.search_service import search_web
import datetime


# ==================== RESEARCH AGENT FUNCTION ====================

def research_agent(state: CampaignState) -> CampaignState:
    """
    Research Agent - Market Analysis & Insights (LLM-Powered)
    
    Args:
        state: CampaignState with manager_output and brief
    
    Returns:
        Updated CampaignState with research_output (5 fields JSON)
    
    Process:
    1. Extract manager output and brief from state
    2. Load research prompt template
    3. Send to LLM for comprehensive market research
    4. Parse LLM response to get 5 research fields
    5. Update state with research output
    """
    
    logger.info("\n" + "=" * 80)
    logger.info("🔍 RESEARCH AGENT ACTIVATED")
    logger.info("=" * 80)
    
    # ========== STEP 1: READ MANAGER OUTPUT ==========
    logger.info("\n[STEP 1] Reading manager output from state...")
    logger.info("-" * 80)
    
    if not state.manager_output:
        raise ValueError("No manager_output found in state")
    
    try:
        manager_data = json.loads(state.manager_output)
    except Exception as e:
        raise ValueError(f"Failed to parse manager_output: {e}")
    
    campaign_name = manager_data.get('campaign_name', 'Unknown Campaign')
    brand_name = manager_data.get('brand_name', 'Unknown Brand')
    industry = manager_data.get('industry', 'other')
    primary_goal = manager_data.get('primary_goal', 'awareness')
    target_audience = manager_data.get('target_audience', 'general audience')
    brand_voice = manager_data.get('brand_voice', 'professional')
    channels = manager_data.get('channels', [])
    deliverables = manager_data.get('deliverables', [])
    brief = state.brief or "No brief provided"
    
    logger.info(f"✓ Campaign: {campaign_name}")
    logger.info(f"✓ Brand: {brand_name}")
    logger.info(f"✓ Industry: {industry}")
    logger.info(f"✓ Goal: {primary_goal}")
    logger.info(f"✓ Target Audience: {target_audience[:60]}...")
    logger.info(f"✓ Brand Voice: {brand_voice}")
    logger.info(f"✓ Channels: {', '.join(channels)}")
    logger.info(f"✓ Brief: {brief[:60] if brief != 'No brief provided' else 'N/A'}...")
    
    # ========== STEP 2: CONDUCT RESEARCH WITH LLM ==========
    logger.info("\n[STEP 2] Conducting market research with LLM...")
    logger.info("-" * 80)
    logger.info("🔬 Analyzing market landscape with AI...")
    
    # Initialize LLM client
    llm = get_llm_client()
    
    # Format human revision feedback if research is targeted for revision
    is_human_revision = bool(state.human_feedback and state.human_revision_target == "research")
    human_feedback_section = ""
    if is_human_revision:
        existing_research_section = ""
        if state.research_output:
            existing_research_section = (
                "\n\nEXISTING RESEARCH (your previous output — preserve ALL unchanged fields exactly):\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                f"{state.research_output}\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            )
        human_feedback_section = (
            "\n" + "="*80 + "\n"
            "⚠️ HUMAN REVISION FEEDBACK — SURGICAL EDIT MODE:\n"
            "You are in REVISION mode. The user has requested a specific change below.\n"
            "CRITICAL REVISION RULES — MUST FOLLOW:\n"
            "  1. READ the user feedback carefully and identify ONLY which field(s) need changing.\n"
            "  2. ONLY modify what the user explicitly asked for. Nothing else.\n"
            "  3. ALL other fields MUST be copied exactly from EXISTING RESEARCH above.\n"
            "  4. Do NOT regenerate, expand, or improve unchanged fields.\n"
            f"User Feedback: \"{state.human_feedback}\"\n"
            + "="*80
            + existing_research_section
        )

    # Load research prompt and format with campaign data
    prompt = load_prompt(
        "research",
        campaign_name=campaign_name,
        brand_name=brand_name,
        industry=industry,
        primary_goal=primary_goal,
        target_audience=target_audience,
        brand_voice=brand_voice,
        brief=brief,
        channels=', '.join(channels),
        deliverables=', '.join(deliverables),
        human_feedback_section=human_feedback_section
    )
    
    # LiteRAG Real-Time Web Search
    logger.info("   Executing LiteRAG real-time web search...")
    current_year = datetime.date.today().year
    product_name = getattr(state, 'product_name', brand_name) or brand_name
    query_1 = f"{product_name} industry trends {target_audience} {current_year}"
    query_2 = f"{product_name} top competitors market analysis"

    # Pass None as redis_client to let search_web automatically use the shared pool
    result_1 = search_web(query_1, redis_client=None)
    result_2 = search_web(query_2, redis_client=None)

    total_snippets = len(result_1.snippets) + len(result_2.snippets)
    logger.info(f"   LiteRAG retrieved {total_snippets} total snippets for campaign")

    # Build context — ONLY inject if snippets actually exist
    context_parts = []

    if result_1.success and result_1.snippets:
        context_parts.append(
            "REAL-TIME MARKET CONTEXT:\n" +
            "\n".join(f"- {s}" for s in result_1.snippets)
        )

    if result_2.success and result_2.snippets:
        context_parts.append(
            "REAL-TIME COMPETITOR CONTEXT:\n" +
            "\n".join(f"- {s}" for s in result_2.snippets)
        )

    # Collect all sources for UI
    all_sources = []
    for result, qtype in [(result_1, "market"), (result_2, "competitor")]:
        if result.success:
            for src in result.sources:
                all_sources.append({
                    "url": src.url,
                    "title": src.title,
                    "domain": src.domain,
                    "snippet": src.snippet,
                    "query_type": qtype
                })

    if context_parts:
        prompt += "\n\n" + "\n\n".join(context_parts)
    
    logger.info("   Querying LLM with structured output...")

    # Revision runs: lower temperature avoids regenerating unchanged fields;
    # higher token budget compensates for the extra existing-output context
    revision_temperature = 0.3 if is_human_revision else 0.7
    revision_max_tokens = 2500 if is_human_revision else 1500

    if is_human_revision:
        logger.info(f"   [REVISION MODE] temperature={revision_temperature}, max_tokens={revision_max_tokens}")

    # Get structured LLM response with error handling
    research_data, state = safe_llm_call(
        state,
        "Research",
        lambda: llm.generate_structured(prompt, ResearchOutput, temperature=revision_temperature, max_tokens=revision_max_tokens)
    )
    
    if research_data is None:
        return state  # Error already logged in state

    # Attach LiteRAG sources to the output
    research_data.literas_sources = all_sources
    
    # ========== STEP 3: DISPLAY FINDINGS ==========
    logger.info("\n[STEP 3] Research insights generated!")
    logger.info("-" * 80)
    logger.info("✅ Research insights generated by LLM!")
    
    logger.info("\n📊 Market Analysis:")
    logger.info(f"   TAM: {research_data.market_analysis.total_addressable_market}")
    logger.info(f"   Growth: {research_data.market_analysis.growth_rate}")
    logger.info(f"   Trends: {', '.join(research_data.market_analysis.market_trends[:2])}...")
    
    logger.info("\n🏆 Competitor Analysis:")
    logger.info(f"   Top Competitors: {', '.join(research_data.competitor_analysis.top_competitors)}")
    logger.info(f"   Differentiation: {research_data.competitor_analysis.differentiation_opportunity[:60]}...")
    
    logger.info("\n👥 Audience Insights:")
    logger.info(f"   Pain Points: {', '.join(research_data.audience_insights.pain_points[:3])}...")
    logger.info(f"   Motivations: {', '.join(research_data.audience_insights.motivations[:2])}...")
    logger.info(f"   Channels: {', '.join(research_data.audience_insights.preferred_channels)}")
    
    logger.info("\n💡 Market Opportunities:")
    for opp in research_data.market_opportunities[:2]:
        logger.info(f"   • {opp}")
    
    logger.info("\n🎯 Recommended Approach:")
    logger.info(f"   {research_data.recommended_approach[:80]}...")
    
    # ========== STEP 4: WRITE TO STATE ==========
    logger.info("\n[STEP 4] Writing to state...")
    logger.info("-" * 80)
    
    research_output_json = research_data.model_dump_json(indent=2)
    
    state.research_output = research_output_json
    state.status = "research_complete"
    
    logger.info("✅ State updated:")
    logger.info(f"   research_output: {len(research_output_json)} characters")
    logger.info(f"   status: {state.status}")
    
    logger.info("\n" + "=" * 80)
    logger.info("✅ RESEARCH AGENT COMPLETE")
    logger.info("=" * 80)
    
    return state


# ==================== MAIN EXECUTION ====================

if __name__ == "__main__":
    logger.info("\n" + "="*80)
    logger.info("⚠️  This is the agent module file.")
    logger.info("    To test the Research Agent, run: python examples/run_research.py")
    logger.info("    To customize input, edit: examples/inputs/campaign_input.json")
    logger.info("="*80)
