"""
RESEARCH AGENT - Market Analysis, Competitive Intel & Customized Insights

Role: Market Researcher / Competitive Analyst / Audience Intelligence

INPUT (From Manager Agent + State):
  FROM state:
    ✅ brief: User's campaign brief (context for research insights)
  
  FROM manager_output (fields needed for research):
    ✅ campaign_name: Campaign identifier
    ✅ brand_name: Brand identifier
    ✅ industry: Industry context for market analysis
    ✅ primary_goal: Campaign goal for audience insights
    ✅ target_audience: Detailed audience for customization
    ✅ brand_voice: Tone for personalization
    ✅ channels: Recommended channels from manager
    ✅ deliverables: Recommended deliverables from manager

OUTPUT (5 Fields - JSON - Research foundation for Strategy & Copywriter):
  1. market_analysis: TAM, growth_rate, market_trends (LLM-generated by industry)
  2. competitor_analysis: top_competitors, differentiation_opportunity (LLM-generated)
  3. audience_insights: pain_points, motivations, preferred_channels (LLM-customized)
  4. market_opportunities: Industry-specific growth opportunities (LLM-generated)
  5. recommended_approach: Strategic approach (LLM-personalized)

HOW IT WORKS:
1. Extract fields from manager_output and state
2. Load research prompt template
3. Send campaign context to LLM for analysis
4. LLM generates customized research insights
5. Return 5 fields for Strategy Agent

KEY PRINCIPLE:
Research = AI-Powered Market Intelligence
- LLM analyzes industry, competitors, and audience
- Generates context-aware, specific insights
- No hardcoded data - fully dynamic research
- Uses prompt template from utils/prompts/research_prompt.txt
"""

import sys
from pathlib import Path
import json
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add project root to path so imports work
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.state import CampaignState
from llm import get_llm_client
from utils.prompt_loader import load_prompt
from utils.error_handler import safe_llm_call
from schemas import ResearchOutput


# ==================== RESEARCH AGENT FUNCTION ====================

def research_agent(state: CampaignState) -> CampaignState:
    """
    Research Agent - Market Analysis & Insights (LLM-Powered)
    
    Args:
        state: CampaignState with manager_output and brief
    
    Returns:
        Updated CampaignState with research_output (5 fields JSON)
    
    Process:
    1. Extract manager output and brief from state
    2. Load research prompt template
    3. Send to LLM for comprehensive market research
    4. Parse LLM response to get 5 research fields
    5. Update state with research output
    """
    
    print("\n" + "=" * 80)
    print("🔍 RESEARCH AGENT ACTIVATED")
    print("=" * 80)
    
    # ========== STEP 1: READ MANAGER OUTPUT ==========
    print("\n[STEP 1] Reading manager output from state...")
    print("-" * 80)
    
    if not state.manager_output:
        raise ValueError("No manager_output found in state")
    
    try:
        manager_data = json.loads(state.manager_output)
    except Exception as e:
        raise ValueError(f"Failed to parse manager_output: {e}")
    
    campaign_name = manager_data.get('campaign_name', 'Unknown Campaign')
    brand_name = manager_data.get('brand_name', 'Unknown Brand')
    industry = manager_data.get('industry', 'other')
    primary_goal = manager_data.get('primary_goal', 'awareness')
    target_audience = manager_data.get('target_audience', 'general audience')
    brand_voice = manager_data.get('brand_voice', 'professional')
    channels = manager_data.get('channels', [])
    deliverables = manager_data.get('deliverables', [])
    brief = state.brief or "No brief provided"
    
    print(f"✓ Campaign: {campaign_name}")
    print(f"✓ Brand: {brand_name}")
    print(f"✓ Industry: {industry}")
    print(f"✓ Goal: {primary_goal}")
    print(f"✓ Target Audience: {target_audience[:60]}...")
    print(f"✓ Brand Voice: {brand_voice}")
    print(f"✓ Channels: {', '.join(channels)}")
    print(f"✓ Brief: {brief[:60] if brief != 'No brief provided' else 'N/A'}...")
    
    # ========== STEP 2: CONDUCT RESEARCH WITH LLM ==========
    print("\n[STEP 2] Conducting market research with LLM...")
    print("-" * 80)
    print("🔬 Analyzing market landscape with AI...")
    
    # Initialize LLM client
    llm = get_llm_client()
    
    # Load research prompt and format with campaign data
    prompt = load_prompt(
        "research",
        campaign_name=campaign_name,
        brand_name=brand_name,
        industry=industry,
        primary_goal=primary_goal,
        target_audience=target_audience,
        brand_voice=brand_voice,
        brief=brief,
        channels=', '.join(channels),
        deliverables=', '.join(deliverables)
    )
    
    print("   Querying LLM with structured output...")
    
    # Get structured LLM response with error handling
    research_data, state = safe_llm_call(
        state,
        "Research",
        lambda: llm.generate_structured(prompt, ResearchOutput, temperature=0.7, max_tokens=1500)
    )
    
    if research_data is None:
        return state  # Error already logged in state
    
    # ========== STEP 3: DISPLAY FINDINGS ==========
    print("\n[STEP 3] Research insights generated!")
    print("-" * 80)
    print("✅ Research insights generated by LLM!")
    
    print("\n📊 Market Analysis:")
    print(f"   TAM: {research_data.market_analysis.total_addressable_market}")
    print(f"   Growth: {research_data.market_analysis.growth_rate}")
    print(f"   Trends: {', '.join(research_data.market_analysis.market_trends[:2])}...")
    
    print("\n🏆 Competitor Analysis:")
    print(f"   Top Competitors: {', '.join(research_data.competitor_analysis.top_competitors)}")
    print(f"   Differentiation: {research_data.competitor_analysis.differentiation_opportunity[:60]}...")
    
    print("\n👥 Audience Insights:")
    print(f"   Pain Points: {', '.join(research_data.audience_insights.pain_points[:3])}...")
    print(f"   Motivations: {', '.join(research_data.audience_insights.motivations[:2])}...")
    print(f"   Channels: {', '.join(research_data.audience_insights.preferred_channels)}")
    
    print("\n💡 Market Opportunities:")
    for opp in research_data.market_opportunities[:2]:
        print(f"   • {opp}")
    
    print("\n🎯 Recommended Approach:")
    print(f"   {research_data.recommended_approach[:80]}...")
    
    # ========== STEP 4: WRITE TO STATE ==========
    print("\n[STEP 4] Writing to state...")
    print("-" * 80)
    
    research_output_json = research_data.model_dump_json(indent=2)
    
    state.research_output = research_output_json
    state.status = "research_complete"
    
    print("✅ State updated:")
    print(f"   research_output: {len(research_output_json)} characters")
    print(f"   status: {state.status}")
    
    print("\n" + "=" * 80)
    print("✅ RESEARCH AGENT COMPLETE")
    print("=" * 80)
    
    return state


# ==================== MAIN EXECUTION ====================

if __name__ == "__main__":
    print("\n" + "="*80)
    print("⚠️  This is the agent module file.")
    print("    To test the Research Agent, run: python examples/run_research.py")
    print("    To customize input, edit: examples/inputs/campaign_input.json")
    print("="*80)
